# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField(default=0)),
                ('movie_name', models.CharField(default='name', max_length=30)),
                ('release_date', models.CharField(default='date', max_length=15)),
                ('video_release', models.CharField(max_length=20, null=True)),
                ('imbd_link', models.CharField(default='IMD', max_length=100)),
                ('unknown', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
                ('adventure', models.IntegerField(default=0)),
                ('animation', models.IntegerField(default=0)),
                ('childrens', models.IntegerField(default=0)),
                ('comedy', models.IntegerField(default=0)),
                ('crime', models.IntegerField(default=0)),
                ('documentary', models.IntegerField(default=0)),
                ('drama', models.IntegerField(default=0)),
                ('fantasy', models.IntegerField(default=0)),
                ('filmnoir', models.IntegerField(default=0)),
                ('war', models.IntegerField(default=0)),
                ('western', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='g', max_length=1)),
                ('occupation', models.CharField(default='occupation', max_length=20)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('timestamp', models.IntegerField(default=1)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movierating.Movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movierating.Rater')),
            ],
        ),
    ]
