# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movieid',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='userid',
            new_name='rater',
        ),
        migrations.AlterField(
            model_name='rater',
            name='zipcode',
            field=models.CharField(default='zipcode', max_length=15),
        ),
    ]
